### ISSUE TITLE
scauzjshixun.yinghuaonline.com华农英华无法使用强制登录

### ISSUE THREAD

**Issue by JerryADS** [aoaostar/cdn#1]
https://scauzjshixun.yinghuaonline.com/user/login
使用强制登录会提示选择学校

**Comment by aoaostar** [comment]
https://mooc.yinghuaonline.com/user/login
用这个登录，选择正确的学校即可，确定别选错了，有些学校有两个，一个学校一个实训平台的，选错了，会没有课程

**Comment by JerryADS** [comment]
scauzjshixun.yinghuaonline.com
可是我们学习要求使用这个来学习，我是这个实训平台才有课程。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aoaostar/cdn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 下午2:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aoaostar/cdn] scauzjshixun.yinghuaonline.com华农英华无法使用强制登录 (Issue #1)





 
https://mooc.yinghuaonline.com/user/login
 用这个登录，选择正确的学校即可，确定别选错了，有些学校有两个，一个学校一个实训平台的，选错了，会没有课程
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aoaostar** [comment]
数据是相通的，都是yinghuaonline.com，学校搞个二级系统就是免除了选择学校平台那一步而已
你在哪看的，两边都有记录

**Comment by JerryADS** [comment]
没，数据不互通的，我是在实训平台看的，mooc那的账号密码和实训平台的账号密码都不一样的。我现在在实训平台被封了7天，强制登陆又用不了，头疼


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aoaostar/cdn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 下午5:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aoaostar/cdn] scauzjshixun.yinghuaonline.com华农英华无法使用强制登录 (Issue #1)





 
数据是相通的，都是yinghuaonline.com，学校搞个二级系统就是免除了选择学校平台那一步而已
 你在哪看的，两边都有记录
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aoaostar** [comment]
不存在的，你肯定是选错了
![image](https://user-images.githubusercontent.com/86001674/153165373-23af80b3-94bd-4378-854d-a0c9e9d9a8ab.png)

**Comment by JerryADS** [comment]
哦哦看到了，谢谢，原来这里还可以选实训平台啊，才发现，真的谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aoaostar/cdn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aoaostar/cdn] scauzjshixun.yinghuaonline.com华农英华无法使用强制登录 (Issue #1)





 
不存在的，你肯定是选错了
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
