### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by blacker0403** [aoaostar/cdn#11]
被封号了怎么办，不可以强制登录

**Comment by aoaostar** [comment]
提issue好好提，带图说清楚，提了一个就不要新开了
什么情况不可以强制登录了，什么也不说，还得我来问你？

**Comment by blacker0403** [comment]
![QQ图片20220619222518](https://user-images.githubusercontent.com/95286182/174485858-a11fc783-55b1-4ba2-ae97-6b414a2fdd4b.png)
抱歉，是我描述不够清除给你造成了麻烦。我遇到的情况是图中这样的，现在登录不进去了怎么办

**Comment by aoaostar** [comment]
> ![QQ图片20220619222518](https://user-images.githubusercontent.com/95286182/174485858-a11fc783-55b1-4ba2-ae97-6b414a2fdd4b.png) 抱歉，是我描述不够清除给你造成了麻烦。我遇到的情况是图中这样的，现在登录不进去了怎么办

脚本没运行
你的学校不是凯康实训，需要自行添加学校的域名
具体操作，参考readme
