### ISSUE TITLE
一直卡在获取课程号等阶段

### ISSUE THREAD

**Issue by chenyingchi** [aoaostar/cdn#13]
能登进去,但一直会卡在获取课程号什么的阶段

**Comment by aoaostar** [comment]
> 能登进去,但一直会卡在获取课程号什么的阶段

运行截图，版本号，看一下
另外，可以尝试重新安装最新版本的脚本

**Comment by chenyingchi** [comment]
![2022-07-15](https://user-images.githubusercontent.com/90334523/179184923-c8e45364-e557-409e-bb3b-1bab3d48cf9c.png)

**Comment by aoaostar** [comment]
更新至最新版本即可



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月15日(周五) 下午4:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aoaostar/cdn] 一直卡在获取课程号等阶段 (Issue #13)
