### ISSUE TITLE
新网址 NEW URL

### ISSUE THREAD

**Issue by jinsesf** [aoaostar/cdn#14]
yit.daixiwangluo.com
yit.pinlankeji.com

**Comment by aoaostar** [comment]
Oh，伙计，你火星了哦，最新版自助添加平台了哦
![image](https://user-images.githubusercontent.com/86001674/179340247-9d383997-45f8-4da9-9aeb-aa5c0ff32f29.png)

**Comment by happygameone** [comment]
我添加以后没有用啊

**Comment by jinsesf** [comment]
1





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月13日(周二) 上午9:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aoaostar/cdn] 新网址 NEW URL (Issue #14)




 
Closed #14 as completed.
