### ISSUE TITLE
大佬新版本会封号

### ISSUE THREAD

**Issue by xindong-bit** [aoaostar/cdn#15]
大佬新版本会封号，之前的版本成功刷完了一个科目，后来不知道什么时候自动更新的新版本，只要开着插件登陆，还没刷过题呢，第二天就封号了，请问这是什么原因？

**Comment by RejectivesD** [comment]
> 大佬新版本会封号，之前的版本成功刷完了一个科目，后来不知道什么时候自动更新的新版本，只要开着插件登陆，还没刷过题呢，第二天就封号了，请问这是什么原因？

**Comment by aoaostar** [comment]
可能是被检测到了吧。。。
正常使用就用普通登录吧
