### ISSUE TITLE
视频播放完后暂停,影响效率

### ISSUE THREAD

**Issue by commingling** [aoaostar/cdn#17]
常时间播放完后暂停,建议添加定时刷新功能

**Comment by aoaostar** [comment]
不知道你说的什么，这门课进度满了完直接下一课了，哪来的暂停

**Comment by commingling** [comment]
好吧,

**Comment by commingling** [comment]
// 刷新当前页面
        window.setTimeout(function(){
            window.location.reload();
        },200000);
我自己加了一个刷新逻辑.
我的视频播放完一个视频之后,经常暂停,还得手动刷新一下

**Comment by aoaostar** [comment]
你是最小化了窗口，然后干别的事情去了吧  
如果是的话看一下常见问题

**Comment by aoaostar** [comment]
> ```
>     // 刷新当前页面
>     window.setTimeout(function(){
>         window.location.reload();
>     },200000);
> ```
> 
> 我自己加了一个刷新逻辑. 我的视频播放完一个视频之后,经常暂停,还得手动刷新一下

不知道你有没有刷完，我写了个新的，一天就能全部刷完，你看看我的`mooc`仓库吧
