### ISSUE TITLE
插件

### ISSUE THREAD

**Issue by kkuang66** [aoaostar/cdn#18]
老哥，学习进度已经100%，但是学习时长没有达到课程要求少了70多分钟

**Comment by aoaostar** [comment]
进度100%就可以了

**Comment by kkuang66** [comment]
![image](https://user-images.githubusercontent.com/96602992/204791576-109801c4-51d4-4617-a4c7-c1be09c4820a.png)
这个wen问题不大吧

**Comment by kkuang66** [comment]
提示说会记录学习时间
