### ISSUE TITLE
标题

### ISSUE THREAD

**Issue by jeiueieeje** [aoaostar/cdn#19]
https://mooc.bxait.cn/user/node?courseId=1011040&chapterId=1095525&nodeId=1442687刷课加载不出来能看看咋回事吗？谢谢小姐姐

**Comment by aoaostar** [comment]
脚本有个库被人举报了，然后管理删掉了，所以现在已经无法使用了，所以，用新版客户端版本吧
地址在油猴脚本说明里写了
