### ISSUE TITLE
实训平台账号被封禁了，强制登录无法使用

### ISSUE THREAD

**Issue by Marktusi** [aoaostar/cdn#2]
实训平台的强制登录没有作用，教程中给的链接打开的是另外的平台
[屏幕录制2022-02-10 09.04.25.zip](https://github.com/aoaostar/cdn/files/8037234/2022-02-10.09.04.25.zip)
。

**Comment by aoaostar** [comment]
已经写清楚了
https://github.com/aoaostar/cdn/tree/master/yinghuaonline#%E5%B0%81%E5%8F%B7%E5%BC%BA%E7%99%BB

**Comment by yx0210** [comment]
你好，请问实训平台封号有没有解决的方案

**Comment by aoaostar** [comment]
> 你好，请问实训平台封号有没有解决的方案

你在答案里问问题（使用封号强登就行）

**Comment by yx0210** [comment]
实训平台的用不了，显示需要填写学校信息，可是并没有这个选项

**Comment by yx0210** [comment]
https://cdcasshixun.yinghuaonline.com/user/login

**Comment by aoaostar** [comment]
> https://cdcasshixun.yinghuaonline.com/user/login

拜托先看readme，别想着一飞冲天，好好看一遍比你来问耗得时间要少，readme写出来不是凑字数的
https://github.com/aoaostar/cdn/tree/master/yinghuaonline#%E5%B0%81%E5%8F%B7%E5%BC%BA%E7%99%BB
![image](https://user-images.githubusercontent.com/86001674/153568913-b28f421f-3547-449f-ae79-8689d9c707d4.png)
