### ISSUE TITLE
同学，我们已经发现您具有相应的网络知识，了解浏览器的调试模式，这挺好的，以下是要对您说的一些警告信息。 video.js?v=1.0.0.0:59 警告：请不要以任何取巧方式进行作弊刷课或帮助其他人刷课，系统已对所有课时的真实性进行统计计算评估，收集数据包括不限于（浏览器头，版本，播放器记录，登录时长，cookie,referer,ip追踪,终端平台，是否符是您的账号，登录过多少个账号，历史登录记录.. 等各种操作数据及ajax随机埋点），一经发现作弊轻则取消学时，重则取消成绩。

### ISSUE THREAD

**Issue by self4m** [aoaostar/cdn#3]
同学，我们已经发现您具有相应的网络知识，了解浏览器的调试模式，这挺好的，以下是要对您说的一些警告信息。
video.js?v=1.0.0.0:59 警告：请不要以任何取巧方式进行作弊刷课或帮助其他人刷课，系统已对所有课时的真实性进行统计计算评估，收集数据包括不限于（浏览器头，版本，播放器记录，登录时长，cookie,referer,ip追踪,终端平台，是否符是您的账号，登录过多少个账号，历史登录记录.. 等各种操作数据及ajax随机埋点），一经发现作弊轻则取消学时，重则取消成绩。

**Comment by aoaostar** [comment]
打开控制台就有的，不用管
屏蔽了video.js就不会显示了

**Comment by self4m** [comment]
已经屏蔽了啊

**Comment by aoaostar** [comment]
> 已经屏蔽了啊

屏蔽了就不会有，还有的话说明你没有屏蔽成功，刷新一下页面吧，不存在继续显示的可能性
