### ISSUE TITLE
你好，首先感谢您的帮助，我们学校的实训平台在英华官网上没有选项，我该怎样实用强制登录

### ISSUE THREAD

**Issue by Accroncer** [aoaostar/cdn#5]
我在英华学堂官网中没有找到燕京理工学院的实训平台该怎么办。https://shixun.yit.edu.cn/user/login

**Comment by Accroncer** [comment]
现在实训平台都换到这个网址了https://shixun.kaikangxinxi.com/user/login

**Comment by aoaostar** [comment]
https://github.com/aoaostar/cdn/tree/master/yinghuaonline#%E5%AE%89%E8%A3%85
https://github.com/aoaostar/cdn/blob/07b7e8c2d1d5a400163545287ecd32f6d0e50f27/yinghuaonline/README.md?plain=1#L16-L26

**Comment by Accroncer** [comment]
这个我已经添加了，但是号给封了，我想使用强制登录，但登录后没有反应

**Comment by Accroncer** [comment]
![微信截图_20220311134342](https://user-images.githubusercontent.com/101379325/157809451-aae93aae-d765-4a75-99a5-db6e8358f61d.png)

**Comment by Accroncer** [comment]
之前的网站选择学校里已经没有实训平台了

**Comment by Accroncer** [comment]
![微信截图_20220311134529](https://user-images.githubusercontent.com/101379325/157809603-221b5c66-75db-4864-92a5-a3d6ddd0dcfd.png)

**Comment by Accroncer** [comment]
现在实训平台已经单独出了一个网站登录用。https://shixun.kaikangxinxi.com/user/login

**Comment by aoaostar** [comment]
知道了，我修一下吧

**Comment by Accroncer** [comment]
好的，麻烦您了

**Comment by aoaostar** [comment]
OK了，更新一下脚本试试吧~

**Comment by blacker0403** [comment]
被封号了怎么办
