### ISSUE TITLE
强登登不进

### ISSUE THREAD

**Issue by coco-Z** [aoaostar/cdn#7]
强登提示登入成功但是页面没有跳转，登不进去

**Comment by aoaostar** [comment]
你的学校平台地址？
https://github.com/aoaostar/cdn/tree/master/yinghuaonline#%E5%B0%81%E5%8F%B7%E5%BC%BA%E7%99%BB

**Comment by coco-Z** [comment]
https://swxyshixun.csuft.edu.cn/user/login

**Comment by aoaostar** [comment]
> https://swxyshixun.csuft.edu.cn/user/login

我测试我们学校是没有问题的
如果可以，你可以把你的账号发我邮箱，我测试一下

**Comment by coco-Z** [comment]
你邮箱是多少

**Comment by coco-Z** [comment]
> > https://swxyshixun.csuft.edu.cn/user/login
> 
> 我测试学校是没有问题的
你的邮箱是多少

**Comment by aoaostar** [comment]
i#aoaostar.com（#改@）

**Comment by coco-Z** [comment]
邮箱发你了

**Comment by coco-Z** [comment]
ok了，谢谢
