### ISSUE TITLE
仍需要输入验证码

### ISSUE THREAD

**Issue by KesonChan** [aoaostar/cdn#8]
能自动跳转，但是80%以上会需要验证码

**Comment by KesonChan** [comment]
没有解决方案了吗

**Comment by aoaostar** [comment]
服务器搬了次家，忘了配置证书了，导致验证码接口无法使用，已经修复了

**Comment by KesonChan** [comment]
谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aoaostar/cdn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月4日(星期三) 晚上9:33
***@***.***&gt;;
抄送:&nbsp;"Keson ***@***.******@***.***&gt;;
主题:&nbsp;Re: [aoaostar/cdn] 仍需要输入验证码 (Issue #8)





 
服务器搬了次家，忘了配置证书了，导致验证码接口无法使用，已经修复了
